#!/usr/bin/env python3
"""Scan logos/ directory and generate js/logo-list.js with filenames array."""

import os
import pathlib

LOGOS_DIR = pathlib.Path(__file__).resolve().parent.parent / "logos"
OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "js" / "logo-list.js"


def main():
    svgs = sorted(
        f.name for f in LOGOS_DIR.iterdir() if f.suffix.lower() == ".svg"
    )
    lines = ", ".join(f"'{name}'" for name in svgs)
    OUTPUT.write_text(
        f"// Auto-generated by scripts/gen_logo_list.py – do not edit\n"
        f"export const LOGOS = [{lines}];\n",
        encoding="utf-8",
    )
    print(f"Generated {OUTPUT} with {len(svgs)} logos")


if __name__ == "__main__":
    main()
